interface:
  refresh_rate: 2000
  theme: superhero
  window:
    height: 650
    title: Audit Wifi App
    width: 500
logging:
  directory: logs
  enabled: true
  format: csv
seuils:
  ping: 100
  rssi:
    bon: -75
    excellent: -65
    faible: -85

wifi:
  collector:
    base_path: logs_moxa
    retry:
      max_retries: 3
      retry_delay: 2
      scan_timeout: 10
      ping_timeout: 10
  thresholds:
    signal_weak: -70
    signal_critical: -80
    packet_loss_warning: 10
    packet_loss_critical: 20
    latency_warning: 100
    latency_critical: 200

network_analyzer:
  moxa_patterns:
    - "[WLAN] Roaming from AP"
    - "Authentication request"
    - "Deauthentication from AP"
    - "SNR:"
    - "Noise floor:"
    - "TransferRingToThread"
    - "AUTH-RECEIVE"
    - "ASSOC-STATE"
    - "WLAN-RECEIVE"
  default_moxa_config:
    min_transmission_rate: 6
    max_transmission_power: 20
    rts_threshold: 512
    roaming_mechanism: signal_strength

moxa_analyzer:
  max_tokens: 2000
