interface:
  refresh_rate: 2000
  theme: superhero
  window:
    height: 650
    title: Audit Wifi App
    width: 500
logging:
  directory: logs
  enabled: true
  format: csv
seuils:
  ping: 100
  rssi:
    bon: -75
    excellent: -65
    faible: -85
