interface:
  refresh_rate: 2000
  theme: darkly
  window:
    width: 500
    height: 650
    title: "Audit Wifi App"
logging:
  directory: logs
  enabled: true
  format: csv
seuils:
  ping: 100
  rssi:
    bon: -75
    excellent: -65
    faible: -85
