# config.yaml
# Paramètres dynamiques
# Ce script est pour PowerShell, ne pas utiliser &&

# Configuration de l'application AuditWifiApp
seuils:
  rssi:
    excellent: -65  # > -65 dBm : Excellent (vert)
    bon: -75       # > -75 dBm : Bon (jaune)
    faible: -85    # ≤ -85 dBm : Faible (rouge)
  ping: 100        # Seuil de ping en ms

interface:
  refresh_rate: 2000  # Taux de rafraîchissement en ms
  window:
    width: 500
    height: 650
    title: "Audit Wifi App"

logging:
  enabled: true
  directory: "logs"
  format: "csv"
